---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-mongo
  labels:
    app: counter-mongo
spec:
  selector:
    matchLabels:
      app: counter
      component: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: counter
        component: mongo
    spec:
      containers:
      - name: counter-mongo
        image: registry.kamilbaran.pl/training/kubernetes/mongo:latest
        resources:


---
apiVersion: v1
kind: Service
metadata:
  name: counter-mongo
  labels:
    app: counter-mongo
spec:
  type: NodePort
  selector:
    app: counter
  ports:
  - port: 80
    targetPort: 80
 