---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-httpd
  labels:
    app: counter-httpd
spec:
  selector:
    matchLabels:
      app: counter
      component: httpd
  replicas: 1
  template:
    metadata:
      labels:
        app: counter
        component: httpd
    spec:
      containers:
      - name: counter-httpd
        image: registry.kamilbaran.pl/training/kubernetes/httpd:latest
        resources:
        ports:
        - name: httpd
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: counter-httpd
  labels:
    app: counter-httpd
spec:
  type: NodePort
  selector:
    app: counter
  ports:
  - port: 80
    #protocol: TCP
    targetPort: httpd
 